package ikame.chatai.ui;

import org.openqa.selenium.By;

public class PageUI_ChatAI {
	public static final By BTN_SKIP = By.id("com.begamob.chatgpt_openai:id/btnSkip");
	public static final String OPTION_LANGUAGE = "//*[@text='&option']";
	public static final By BTN_DONE_LANGUAGE = By.id("com.begamob.chatgpt_openai:id/id_menu_toolbar");
	public static final By BTN_DONE = By.id("com.chatbot.ai.aichat.openaibot.chat:id/y1");
	public static final By BTN_CONTINUE = By.xpath("//*[@text='Continue to app']");
	public static final By TEXT_CHAT_AI = By.id("com.begamob.chatgpt_openai:id/tvAiChat");
	public static final By ICON_CHAT_AI = By.xpath("//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvAiChat']//preceding-sibling::android.widget.ImageView");
	public static final By BTN_SETTING = By.id("com.begamob.chatgpt_openai:id/ivSetting");
	public static final By TEXT_IMAGE_GENERATOR = By.xpath("(//android.widget.LinearLayout[@resource-id='com.begamob.chatgpt_openai:id/llnArt']//android.widget.TextView)[1]");
	public static final By BTN_CREATE_NOW = By.xpath("//android.widget.LinearLayout[@resource-id='com.begamob.chatgpt_openai:id/llnArt']//android.widget.LinearLayout//android.widget.TextView");
	public static final By TAB_AI_ORC_TEXT = By.id("com.begamob.chatgpt_openai:id/llnViewOcr");
	public static final By TAB_SUMMARY_TEXT = By.id("com.begamob.chatgpt_openai:id/llnViewSummary");
	public static final By TEXT_DISCOVER_TOPIC = By.xpath("//android.widget.TextView[@text='Discover topic']");
	public static final By TEXT_VIEW_MORE = By.id("com.begamob.chatgpt_openai:id/tvViewAllTopic");
	public static final By TEXTBOX_ASK_A_QUESTION = By.id("com.begamob.chatgpt_openai:id/homeFm_startChat");
	public static final By BTN_IMAGE = By.id("com.begamob.chatgpt_openai:id/icAddGallery");
	public static final By BTN_VOID_CHAT = By.id("com.begamob.chatgpt_openai:id/ic_voice");
	public static final By BTN_SEND = By.id("com.begamob.chatgpt_openai:id/homeFm_iconStartChat");
	public static final By ICON_CHAT_AI_BOTTOM_BAR = By.id("com.begamob.chatgpt_openai:id/btf_secondIcon");
	public static final By TEXT_CHAT_AI_BOTTOM_BAR = By.id("com.begamob.chatgpt_openai:id/btf_secondTitle");
	public static final By ICON_ASSISTANT = By.id("com.begamob.chatgpt_openai:id/btf_assistant");
	public static final By TEXT_ASSISTANT = By.id("com.begamob.chatgpt_openai:id/btf_assistantTitle");
	public static final By ICON_MIDJ_ART = By.id("com.begamob.chatgpt_openai:id/btf_threeIcon");
	public static final By TEXT_MIDJ_ART = By.id("com.begamob.chatgpt_openai:id/btf_threeTitle");
	public static final By IMG_MEMBER_CLASS = By.id("com.begamob.chatgpt_openai:id/settingFm_iconPremium");
	public static final By TEXT_YOU_ARE_VIP = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateTv2");
	public static final By TEXT_ENJOY_UNLIMITED = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateTvDes2");
	public static final By TAB_WIDGET = By.id("com.begamob.chatgpt_openai:id/fmSettingWidget");
	public static final By TAB_BUBBLE_CHAT = By.id("com.begamob.chatgpt_openai:id/fmSettingBubble");
	public static final By TAB_RESTORE_PERCHASE = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateItemRestore");
	public static final By TAB_ABOUT_US = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateItemAbout");
	public static final By TAB_PRIVACY_POLICY = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateItemPrivacy");
	public static final By TAB_TERM_OF_USE = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateItemTemp");
	public static final By TAB_LANGUAGE = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateItemLanguage");
	public static final By TAB_CONTACTS_SUPPORT = By.id("com.begamob.chatgpt_openai:id/fmSetting_contactSupport");
	public static final By TAB_RATE_APP = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateItemRate");
	public static final By TAB_SEND_FEEDBACK = By.id("com.begamob.chatgpt_openai:id/fmSettingUpdateItemFeedBack");
	public static final By TEXT_PERSONALIZE_YOUR_HOME = By.id("com.begamob.chatgpt_openai:id/fmWidgetTvDes");
	public static final By TEXT_4_1_WIDGET = By.id("com.begamob.chatgpt_openai:id/textView");
	public static final By IMG_4_1_WIDGET = By.id("com.begamob.chatgpt_openai:id/fmWidgetNoTopic");
	public static final By BTN_ADD_TO_HOME_SCREEN_4_1 = By.id("com.begamob.chatgpt_openai:id/fmWidgetTvAddNoTopic");
	public static final By CARD_CHAT_AI = By.id("com.google.android.apps.nexuslauncher:id/widget_preview");
	public static final By BTN_CANCEL = By.xpath("//android.widget.Button[@text='Cancel']");
	public static final By BTN_ADD_TO_HOME_SCREEN = By.xpath("//android.widget.Button[@text='Add to Home screen']");
	public static final By TEXT_4_2_WIDGET = By.id("com.begamob.chatgpt_openai:id/textView2");
	public static final By IMG_4_2_WIDGET = By.id("com.begamob.chatgpt_openai:id/fmWidgetTopic");
	public static final By BTN_ADD_TO_HOME_SCREEN_4_2 = By.id("com.begamob.chatgpt_openai:id/fmWidgetTvAddTopic");
	public static final By BTN_SWITCH = By.id("com.begamob.chatgpt_openai:id/itemSettingSw");
	public static final By TEXT_DISPLAY_OVER_OTHER_APPS = By.id("com.android.settings:id/collapsing_toolbar");
	public static final By APP_CHAT_AI = By.xpath("//android.widget.TextView[@content-desc='ChatAI: AI Chatbot']");
	public static final By TEXT_THANK_YOU_FOR_PURCHASING = By.id("com.chatbot.ai.aichat.openaibot.chat:id/ng");
	public static final By BTN_CANCEL_RESTORE_PERCHASE = By.id("com.chatbot.ai.aichat.openaibot.chat:id/nd");
	public static final By AI_CHAT_CH_PLAY = By.xpath("//*[contains(@text,'AI Chat')]");
	public static final By TEXT_IKAME = By.xpath("//*[contains(@text,'iKame')]");
	public static final By URL_CHORME = By.id("com.android.chrome:id/url_bar");
	public static final By LIST_LANGUAGE = By.id("com.chatbot.ai.aichat.openaibot.chat:id/zr");
	public static final By TEXT_RATE_US = By.id("com.begamob.chatgpt_openai:id/dialogRate_tvDes");
	public static final By BTN_RATE = By.id("com.begamob.chatgpt_openai:id/dialogRate_tv_submit");
	public static final By TEXT_SHARE_WITH = By.id("android:id/chooser_row_text_option");
	public static final By LIST_APP = By.id("android:id/icon");
	public static final By BTN_OK = By.id("com.chatbot.ai.aichat.openaibot.chat:id/nf");
	public static final By ICON_BUBBLE = By.id("com.begamob.chatgpt_openai:id/bubbleView");
	public static final By OPTION_CHAT_AI = By.id("com.begamob.chatgpt_openai:id/viewBubbleChat_model");
	public static final By BTN_DISMISS = By.xpath("//*[contains(@text,'Dismiss')]");
	public static final By BTN_REGENERATE = By.id("com.begamob.chatgpt_openai:id/btnRegenerate");
	public static final By BTN_LEFT = By.id("com.begamob.chatgpt_openai:id/baseHeader_btnLeft");
	public static final By TEXT_RECENT_HISTORY = By.xpath("//android.widget.TextView[@text='Recent history']");
	public static final By LIST_TITLE_IN_RECENT_HISTORY = By.xpath("//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvTitle']");
	public static final By LIST_TITLE_IN_DISCOVER_TOPIC = By.xpath("//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvTitle']");
	public static final By BTN_CLOSE = By.id("com.begamob.chatgpt_openai:id/dialogBtnClose");
	public static final By TEXT_VIEW_MORE_RECENT_HISTORY = By.id("com.begamob.chatgpt_openai:id/tvViewAllHistory");
	public static final By TAB_GENERATE_ART = By.xpath("(//android.widget.HorizontalScrollView[@resource-id='com.begamob.chatgpt_openai:id/tab_layout']//android.widget.TextView)[1]");
	public static final By TAB_WALLPAPERS = By.xpath("(//android.widget.HorizontalScrollView[@resource-id='com.begamob.chatgpt_openai:id/tab_layout']//android.widget.TextView)[2]");
	public static final By TEXT_ENTER_YOUR_PROMPT = By.xpath("//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/fmHomeArtTvInspired']//preceding-sibling::android.widget.TextView");
	public static final By BTN_GET_INSPIRED = By.id("com.begamob.chatgpt_openai:id/fmHomeArtTvInspired");
	public static final By TEXTBOX_PROMPT = By.id("com.begamob.chatgpt_openai:id/fmHomeArtEdtPrompt");
	public static final By BTN_ADVANCED = By.id("com.begamob.chatgpt_openai:id/generateFm_tvAdvanced");
	public static final By BTN_PRIMARY = By.id("com.begamob.chatgpt_openai:id/generateFm_llnPrimaryView");
	public static final By DROPDOWNLIST_CHOOSE_MODEL = By.id("com.begamob.chatgpt_openai:id/generateFm_chooseModel");
	public static final By DROPDOWNLIST_CHOOSE_SETTING = By.id("com.begamob.chatgpt_openai:id/generateFm_advanceSetting");
	public static final By TEXT_CHOOSE_AN_ART_STYLE = By.xpath("//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/generateFm_tvMore']//preceding-sibling::android.widget.TextView");
	public static final By TEXT_MORE = By.id("com.begamob.chatgpt_openai:id/generateFm_tvMore");
	public static final By LIST_ART = By.id("com.begamob.chatgpt_openai:id/tvStyleArt");
	public static final By BTN_GENERATE = By.id("com.begamob.chatgpt_openai:id/fmHomeArtLlGenerate");
	public static final By TEXT_CHOOSE_ACTION = By.id("com.begamob.chatgpt_openai:id/dialogAction_title");
	public static final By BTN_OPEN_CAMERA = By.id("com.begamob.chatgpt_openai:id/dialogAction_btnOpenCamera");
	public static final By BTN_GO_TO_PHOTO = By.id("com.begamob.chatgpt_openai:id/dialogAction_btnSelectPhoto");
	public static final By BTN_CANCEL_ACTION = By.id("com.begamob.chatgpt_openai:id/dialogAction_btnCancel");
	public static final By BTN_TAKE_PHOTO = By.id("com.android.camera2:id/shutter_button");
	public static final By TITLE_CHOOSE_PHOTOS = By.id("com.begamob.chatgpt_openai:id/galleryFm_tvTitle");
	public static final By LIST_IMG = By.id("com.begamob.chatgpt_openai:id/image");
	public static final By BTN_UPLOAD_FILES = By.id("com.begamob.chatgpt_openai:id/summaryFm_uploadFile");
	public static final By BTN_UPLOAD_PHOTOS = By.id("com.begamob.chatgpt_openai:id/summaryFm_uploadImage");
	public static final By IMG_FILE_IMG = By.id("com.begamob.chatgpt_openai:id/summaryFm_imageFind");
	public static final By TEXTBOX_SUMMARY = By.id("com.begamob.chatgpt_openai:id/summaryFm_edt");
	public static final By BTN_SCAN = By.id("com.begamob.chatgpt_openai:id/summaryFm_btnOcr");
	public static final By BTN_SEND_SUMMARY = By.id("com.begamob.chatgpt_openai:id/summaryFm_btnSend");
	public static final By TITLE_ONLY_UPLOAD_PDF = By.id("com.begamob.chatgpt_openai:id/title");
	public static final By BTN_I_GOT_IT = By.id("com.begamob.chatgpt_openai:id/btnIGotIt");
	public static final By BTN_CANCEL_UPLOAD_FILES = By.id("com.begamob.chatgpt_openai:id/btnCancel");
	public static final By LIST_FILE_PDF = By.xpath("//android.widget.TextView[@resource-id='android:id/title']");
	public static final By BTN_UPLOAD_IMG = By.id("com.begamob.chatgpt_openai:id/galleryFm_btnUpload");
	public static final By TEXTBOX_SEARCH = By.id("com.begamob.chatgpt_openai:id/chatFm_llnFile");
	public static final String BTN_IN_ASSISTANT = "//android.widget.LinearLayout[@resource-id='com.begamob.chatgpt_openai:id/llnView']//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvTitle' and @text='&option']";
	public static final By TITLE_ASSISTANT = By.id("com.begamob.chatgpt_openai:id/homeFmSelectTitle");
	public static final By LIST_BTN_IN_ASSISTANT = By.id("com.begamob.chatgpt_openai:id/tvTitle");
	public static final By TITLE_CHAT_AI = By.id("com.begamob.chatgpt_openai:id/baseHeader_tvTitle");
	public static final By TXTBOX_ASK_A_QUESTION = By.id("com.begamob.chatgpt_openai:id/baseHeader_tvTitle");
	public static final By TITLE_VOID_CHAT = By.id("com.begamob.chatgpt_openai:id/voiceTitle");
	public static final By IMG_MIC = By.id("com.begamob.chatgpt_openai:id/voiceAnim");
	public static final By TEXT_LANGUAGE = By.id("com.begamob.chatgpt_openai:id/voiceLanguage");
	public static final By TITLE_HISTORY = By.id("com.begamob.chatgpt_openai:id/baseHeader_tvTitle");
	public static final By BTN_DELETE = By.id("com.begamob.chatgpt_openai:id/baseHeader_btnRight");
	public static final By LIST_TEXT_BOT_CHAT_REPLY = By.id("com.begamob.chatgpt_openai:id/itChatHistoryBotChat");
	public static final By LIST_TEXT_USER_ASK = By.id("com.begamob.chatgpt_openai:id/itChatHistoryUserChat");
	public static final String TEXT_CONTENT_IN_ASSISTANT = "//androidx.recyclerview.widget.RecyclerView[@resource-id='com.begamob.chatgpt_openai:id/rclDetailAllTopic']//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvTitle' and @text='&option']";
	public static final By LIST_TEXT_CARD_IN_ASSISTANT = By.id("//android.widget.GridView[@resource-id='com.begamob.chatgpt_openai:id/rclDetailTopic']//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvTitle']");
	public static final String OPTION_UTILITIES = "//android.widget.TextView[contains(@text,'&option')]";
	public static final By TITLE_UTINITIES = By.id("com.begamob.chatgpt_openai:id/baseHeader_tvTitle");
	public static final By LIST_TEXTBOX = By.id("com.begamob.chatgpt_openai:id/inputText");
	public static final By BUTTON_CONTINUE = By.id("com.begamob.chatgpt_openai:id/topicFm_btnContinue");
	public static final By LIST_ICON = By.id("com.begamob.chatgpt_openai:id/iconTopic");
	public static final By LIST_TITLE_UTILITIES = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id='com.begamob.chatgpt_openai:id/rclDetailAllTopic']//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvTitle']");
	public static final By LIST_DESCRIBE_UTILITIES = By.id("com.begamob.chatgpt_openai:id/tvSubTitle");
	public static final By LIST_NAME_UTILITIES = By.id("com.begamob.chatgpt_openai:id/iconTopic");
	public static final By TAB_GENERATE = By.xpath("(//android.widget.HorizontalScrollView[@resource-id='com.begamob.chatgpt_openai:id/tab_layout']//android.widget.TextView)[1]");
	public static final By DROPDOWN_LIST_CHOOSE_MODEL = By.id("com.begamob.chatgpt_openai:id/generateFm_chooseModel");
	public static final By TEXT_SELECT_MODEL = By.id("com.begamob.chatgpt_openai:id/textTitle");
	public static final By LIST_MODEL = By.xpath("//android.widget.GridView[@resource-id='com.begamob.chatgpt_openai:id/select_rcl']//android.widget.FrameLayout");
	public static final By IMG_MODEL_1 = By.xpath("(//*[@resource-id='com.begamob.chatgpt_openai:id/llnContainer'])[1]");
	public static final By DROPDOWN_LIST_CHOOSE_SETTING = By.id("com.begamob.chatgpt_openai:id/generateFm_advanceSetting");
	public static final By TEXT_ADVANCED_SETTINGS = By.id("com.begamob.chatgpt_openai:id/textTitle");
	public static final By TEXTBOX_NEGATIVE_PROMPT = By.id("com.begamob.chatgpt_openai:id/edtNegativePrompt");
	public static final By BTN_SAVE = By.id("com.begamob.chatgpt_openai:id/btnSave");
	public static final By TEXT_NEGATIVE_PROMPT = By.id("com.begamob.chatgpt_openai:id/tvNegativePrompt");
	public static final By LIST_FLEXBOX = By.id("com.begamob.chatgpt_openai:id/llnAspectRadio");
	public static final By TEXT_SCALE = By.id("com.begamob.chatgpt_openai:id/tvCfgScale");
	public static final By SCALE_SELECTION_BAR = By.id("com.begamob.chatgpt_openai:id/seekbar");
	public static final By ICON_SCALE_1 = By.xpath("(//android.view.ViewGroup[@resource-id='com.begamob.chatgpt_openai:id/llnAspectRadio'])[1]");
	public static final By TEXT_CHOOSE_STYLE_ART = By.id("com.begamob.chatgpt_openai:id/baseHeader_tvTitle");
	public static final By BTN_DONE_STYLE_ART = By.id("com.begamob.chatgpt_openai:id/fmMoreStyleArtTvDone");
	public static final By IMG_RANDOM = By.id("com.begamob.chatgpt_openai:id/llnContainer");
	public static final By BTN_SWITCH_WATERMARK = By.id("com.begamob.chatgpt_openai:id/fmResultArtLlPremium");
	public static final By IMG_RESULT_ART = By.id("com.begamob.chatgpt_openai:id/fmResultArtImv");
	public static final By TEXT_RESULT_PROMPT = By.id("com.begamob.chatgpt_openai:id/fmResultArtTvPrompt");
	public static final By TEXT_RESULT_STYLE = By.id("com.begamob.chatgpt_openai:id/fmResultArtTvStyle");
	public static final By BUTTON_REGENERATE = By.id("com.begamob.chatgpt_openai:id/fmResultArtTvRegenerate");
	public static final By BTN_IMG = By.id("com.begamob.chatgpt_openai:id/fmResultArtImvDownload");
	public static final By BTN_SHARE = By.id("com.begamob.chatgpt_openai:id/fmResultArtImvShare");
	public static final By TEXT_CHOOSE_AN_ART_STYLE_PRIMARY = By.xpath("(//android.widget.LinearLayout[@resource-id='com.begamob.chatgpt_openai:id/generateFm_llnContainerPrimary']//android.widget.TextView)[1]");
	public static final By LIST_IMG_PRIMARY = By.id("com.begamob.chatgpt_openai:id/itStyleArtRlBg");
	public static final By LIST_TITLE_IMG_PRIMARY = By.id("com.begamob.chatgpt_openai:id/itStyleArtTvNameSelect");
	public static final By IMG_PRIMARY1 = By.xpath("(//android.widget.RelativeLayout[@resource-id='com.begamob.chatgpt_openai:id/itStyleArtLlBorder'])[2]");
	public static final By TEXT_POPULAR = By.id("com.begamob.chatgpt_openai:id/fmWall_tvTitlePopular");
	public static final By IMG_WALLPAPERS1 = By.xpath("(//android.widget.ImageView[@resource-id='com.begamob.chatgpt_openai:id/image'])[1]");
	public static final By TEXT_SET_WALLPAPER = By.id("com.begamob.chatgpt_openai:id/baseHeader_tvTitle");
	public static final By BTN_SET_WALLPAPER = By.id("com.begamob.chatgpt_openai:id/btnSetWallpaper");
	public static final By BTN_BACK = By.id("com.begamob.chatgpt_openai:id/fmResultArtImvBack");
	public static final By IMG_SUCCESS = By.id("com.begamob.chatgpt_openai:id/fmResultArtLatDownloaded");
	public static final By TEXT_NUMBER_FREE_TIMES = By.id("com.begamob.chatgpt_openai:id/generateFm_TvNumber1");
	public static final By TEXT_CONTENT_ANSWER = By.id("com.begamob.chatgpt_openai:id/chatItemListLeftText");
	public static final By BUTTON_SEND = By.id("com.begamob.chatgpt_openai:id/chatFm_btnSend");
	public static final By TEXTBOX_ANSWER_USER = By.id("com.begamob.chatgpt_openai:id/chatItemListRightText");
	public static final By ICON_HISTORY = By.id("com.begamob.chatgpt_openai:id/baseHeader_btnCustom");
	public static final By ICON_LOUDSPEAKER = By.id("com.begamob.chatgpt_openai:id/baseHeader_btnRight");
	public static final By BTN_COPY = By.id("com.begamob.chatgpt_openai:id/btnCopy");
	public static final By BUTTON_SHARE = By.id("com.begamob.chatgpt_openai:id/btnShare");
	public static final By TXTB_ASK_A_QUESTION = By.id("com.begamob.chatgpt_openai:id/chatFm_edt");
	public static final String CHAT_AI_RELLY = "(//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/chatItemListLeftText'])[&option]";
	public static final String TEXT_USER_ASK = "(//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/chatItemListRightText'])[&option]";
	public static final By TEXT_NUMBER_OF_CHARACTERS = By.id("com.begamob.chatgpt_openai:id/chatFmLimitText");
	public static final By OPTION_APPLICATION = By.id("android:id/icon");
	public static final String CHAT_AI_RELLY_HISTORY = "(//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/itChatHistoryBotChat'])[&option]";
	public static final String TEXT_USER_ASK_HISTORY = "(//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/itChatHistoryUserChat'])[&option]";
	public static final By TEXT_DELETE = By.id("com.begamob.chatgpt_openai:id/baseHeader_tvTitle");
	public static final By BTN_CHOOSE_ALL = By.id("com.begamob.chatgpt_openai:id/baseHeader_btnRight");
	public static final String CHAT_AI_RELLY_DELETE = "(//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/chatItemListLeftText'])[&option]";
	public static final String TEXT_USER_ASK_DELETE = "(//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/chatItemListRightText'])[&option]";
	public static final String OPTION_CHOOSE = "(//android.widget.CheckBox[@resource-id='com.begamob.chatgpt_openai:id/itChatHistory_cb'])[&option]";
	public static final By BUTTON_DELETE = By.id("com.begamob.chatgpt_openai:id/fmHistory_delete");
	public static final By BTN_CANCEL_DELETE = By.id("com.begamob.chatgpt_openai:id/dialogConfrirmDelete_tvCancel");
	public static final By TEXT_CONFIRM_DELETE = By.id("com.begamob.chatgpt_openai:id/dialogConfrirmDelete_tvDes");
	public static final By TEXT_SUBMIT_DELETE = By.id("com.begamob.chatgpt_openai:id/dialogConfrirmDelete_tvSubmit");
	public static final By BTN_TAKE_SCREEN = By.id("com.android.camera2:id/bottombar_capture");
	public static final By BTN_DONE_TAKE_SCREEN = By.id("com.android.camera2:id/done_button");
	public static final By BUTTON_DONE = By.id("com.begamob.chatgpt_openai:id/btnDone");
	public static final By BTN_RETAKE = By.id("com.android.camera2:id/retake_button");
	public static final By BTN_CANCEL_IMG = By.id("com.android.camera2:id/cancel_button");
	public static final By BTN_ROTATE = By.id("com.begamob.chatgpt_openai:id/icRotate");
	public static final By TEXT_ENTER_PROMPTS = By.id("com.begamob.chatgpt_openai:id/chatItemListLeftText");
	public static final By BTN_CLOSE_IMG = By.id("com.begamob.chatgpt_openai:id/btnCloseImageInput");
	public static final By TEXT_SELECT_MODEL_GPT = By.id("com.begamob.chatgpt_openai:id/tvSelectModel");
	public static final By CARD_GPT_3_5 = By.id("com.begamob.chatgpt_openai:id/llnView35");
	public static final By CARD_GPT_4_0 = By.id("com.begamob.chatgpt_openai:id/llnViewGpt4");
	public static final By BTN_CONTINUE_TO_CHAT = By.id("com.begamob.chatgpt_openai:id/btnContinue");
	public static final By TEXT_GPT_UPGRADE = By.xpath("//android.widget.TextView[@text='GPT4 - Upgrade']");
	public static final By TAB_YEARLY = By.id("com.begamob.chatgpt_openai:id/act_layoutPremiumYear");
	public static final By TAB_WEEKLY = By.id("com.begamob.chatgpt_openai:id/premiumAct_btnPremium");
	public static final By BTN_CLOSE_UPGRADE = By.id("com.begamob.chatgpt_openai:id/premiumActBtnClose");
	public static final By ICON_FLIP = By.id("com.begamob.chatgpt_openai:id/icFlip");
	public static final By IMG_PHOTO_TAKEN = By.id("com.begamob.chatgpt_openai:id/imageInput");
	public static final By IMG_1 = By.xpath("(//android.widget.ImageView[@resource-id='com.begamob.chatgpt_openai:id/image'])[1]");
	public static final By TEXT_TRY_TO_SAY_SOMETHING = By.id("com.begamob.chatgpt_openai:id/voiceText");
	public static final By TITLE_CHANGE_LANGUAGE = By.id("com.begamob.chatgpt_openai:id/textTitleChangeLanguage");
	public static final By ICON_IV_BACK = By.id("com.begamob.chatgpt_openai:id/ivBack");
	public static final By LIST_LANGUAGE_MIC = By.id("com.begamob.chatgpt_openai:id/language");
	public static final By LIST_FLAG_MIC = By.id("com.begamob.chatgpt_openai:id/flag");
	public static final By TEXT_CHOOSE_VERSION = By.xpath("//android.widget.TextView[@text='Choose version']");
	public static final By TEXT_CHOOSE_MODEL = By.xpath("//android.widget.TextView[@text='Choose Model']");
	public static final By TEXT_ADVANCED_SETTING = By.xpath("//android.widget.TextView[@text='Advanced Settings']");
	public static final By TEXT_WATERMARK = By.xpath("//android.widget.TextView[@text='Watermark']");
	public static final By SWITCH_WATERMARK = By.id("com.begamob.chatgpt_openai:id/fmResultArtSw");
	public static final By BLOCK_RANDOM = By.xpath("//android.widget.TextView[@text='Random']");
	public static final By TEXT_ERROR = By.id("com.begamob.chatgpt_openai:id/dlFailArt_tvTitle");
	public static final By TEXT_DECSRIPTION_ERROR = By.id("com.begamob.chatgpt_openai:id/dlFailArt_tvDes");
	public static final By BUTTON_I_GOT_IT = By.id("com.begamob.chatgpt_openai:id/dlFailArt_tvSubmit");
	public static final String TEXT_NAME_ART = "(//android.widget.TextView[@resource-id='com.begamob.chatgpt_openai:id/tvStyleArt'])[&option]";
	public static final By BLOCK_ABSTRACT_VIBRANT = By.xpath("//android.widget.TextView[@text='Abstract Vibrant']");
	public static final By BLOCK_AMAZONIAN = By.xpath("//android.widget.TextView[@text='Amazonian']");
	public static final By BLOCK_ANIME_V2 = By.xpath("//android.widget.TextView[@text='Anime V2']");
	public static final By TEXT_ASPECT_RATIO = By.xpath("//android.widget.TextView[@text='Aspect Ratio']");
	public static final By BLOCK_AQUATIC = By.xpath("//android.widget.TextView[@text='Aquatic']");
	public static final By BLOCK_ARCHITECTURE = By.xpath("//android.widget.TextView[@text='Architecture']");
	public static final By BLOCK_CANDYLAND = By.xpath("//android.widget.TextView[@text='Candyland']");
	public static final By BLOCK_AVATAR = By.xpath("//android.widget.TextView[@text='Avatar']");
	public static final By BLOCK_BAUHAUS = By.xpath("//android.widget.TextView[@text='Bauhaus']");
	public static final By BLOCK_PAINTING = By.xpath("//android.widget.TextView[@text='Painting']");
	public static final By BLOCK_ANIME = By.xpath("//android.widget.TextView[@text='Anime']");
	public static final By BLOCK_MAGICAL = By.xpath("//android.widget.TextView[@text='Magical']");
	public static final By TEXT_FREE_TRES_LEFT_PRIMARY= By.id("com.begamob.chatgpt_openai:id/generateFm_TvNumber2");
	 
}
